version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 14
    commands:
      - echo "Installation des dépendances système"
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - composer --version
      - npm install -g npm@latest
  pre_build:
    commands:
      - echo "Démarrage de la phase pre_build"
      - echo "Mise à jour des dépendances système"
      - composer install --no-dev --optimize-autoloader
      - npm install
  build:
    commands:
      - echo "Démarrage de la phase build"
      - npm run prod
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
  post_build:
    commands:
      - echo "Démarrage de la phase post_build"
      - zip -r deployment-package.zip . -x "node_modules/*" "vendor/*" "storage/logs/*" ".env" ".git/*"
      - echo "Déploiement sur Elastic Beanstalk"
      - eb init -p php-8.2 my-app --region us-west-2
      - eb use Hocine-php-env
      - eb deploy

artifacts:
  files:
    - deployment-package.zip